export const SIGNUP_START="SIGNUP_START";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const SIGNUP_FAIL="SIGNUP_FAIL";

export const SIGNIN_START="SIGNIN_START";
export const SIGNIN_SUCCESS="SIGNIN_SUCCESS";
export const SIGNIN_FAIL="SIGNIN_FAIL";

export const SIGNOUT_START="SIGNOUT_START";
export const SIGNOUT_SUCCESS="SIGNOUT_SUCCESS";
export const SIGNOUT_FAIL="SIGNOUT_FAIL";

export const SET_USER="SET_USER";

export const GOOGLE_SIGNIN_START="GOOGLE_SIGNIN_START";
export const GOOGLE_SIGNIN_SUCCESS="GOOGLE_SIGNIN_SUCCESS";
export const GOOGLE_SIGNIN_FAIL="GOOGLE_SIGNIN_FAIL";

export const SET_EXERCISES="SET_EXERCISES";
export const SELECTED_EXERCISE="SELECTED_EXERCISE";

